version: '3.8'

services:
  app:
    image: golang:1
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:password@localhost:5432/tododb?sslmode=disable
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    command: go run main.go
