services:

  app:
    build: ./10.1
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/tododb?sslmode=disable
    volumes:
      - ./10.1:/app
    ports:
      - "8989:8989"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: