services:

  app:
    build: ./10.1
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/tododb?sslmode=disable
    volumes:
      - ./10.1:/app
    ports:
      - "8989:8989"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailapp:
    build: ./10.8
    container_name: mailapp
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/tododb?sslmode=disable
      - MAIL_SERVER=http://mailhog:1025
      - MAIL_FROM=todo-reminder@example.com
      - MAIL_TO=user@example.com
    volumes:
      - ./10.8:/app
    ports:
      - "9898:9898"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"


volumes:
  db_data: